### ISSUE TITLE
Working with WECHATY_PUPPET=wechaty-puppet-oicq broken

### ISSUE THREAD

**Issue by anaivebird** [wechaty/wechaty-puppet-oicq#5]
```
15:18:16 VERB PuppetManager resolveName(wechaty-puppet-oicq)
CustomError: Cannot find package 'wechaty-puppet-oicq' imported from /home/anelderly/wechaty-getting-started/node_modules/wechaty/dist/esm/src/puppet-manager.js
    at packageResolve (/home/anelderly/wechaty-getting-started/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:774:9)
    at moduleResolve (/home/anelderly/wechaty-getting-started/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:815:18)
    at Object.defaultResolve (/home/anelderly/wechaty-getting-started/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:929:11)
    at /home/anelderly/wechaty-getting-started/node_modules/ts-node/src/esm.ts:68:38
    at Generator.next (<anonymous>)
    at /home/anelderly/wechaty-getting-started/node_modules/ts-node/dist/esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/anelderly/wechaty-getting-started/node_modules/ts-node/dist/esm.js:4:12)
    at resolve (/home/anelderly/wechaty-getting-started/node_modules/ts-node/dist/esm.js:32:16)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at Loader.import (internal/modules/esm/loader.js:165:28)
    at importModuleDynamically (internal/modules/esm/translators.js:114:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at Function.resolveName (file:///home/anelderly/wechaty-getting-started/node_modules/wechaty/src/puppet-manager.ts:118:26)
    at Function.resolve (file:///home/anelderly/wechaty-getting-started/node_modules/wechaty/src/puppet-manager.ts:72:33)
    at Wechaty.initPuppet (file:///home/anelderly/wechaty-getting-started/node_modules/wechaty/src/wechaty.ts:394:48)
    at Wechaty.start (file:///home/anelderly/wechaty-getting-started/node_modules/wechaty/src/wechaty.ts:722:18)
15:18:16 ERR Wechaty start() exception: Cannot find package 'wechaty-puppet-oicq' imported from /home/anelderly/wechaty-getting-started/node_modules/wechaty/dist/esm/src/puppet-manager.js
15:18:16 ERR StarterBot Error: Cannot find package 'wechaty-puppet-oicq' imported from /home/anelderly/wechaty-getting-started/node_modules/wechaty/dist/esm/src/puppet-manager.js
```

Working with WECHATY_PUPPET=wechaty-puppet-oicq still not works, any advice for further development? ESM branch code has been released to [wechaty-puppet-oicq@0.1.5](https://www.npmjs.com/package/wechaty-puppet-oicq/v/0.1.5)

**Comment by huan** [comment]
> Cannot find package 'wechaty-puppet-oicq' 

The above error message is clear enough: you have not installed this module.

You need to install it before using it:

```sh
npm install wechaty-puppet-oicq`
```

**Comment by anaivebird** [comment]
```
17:30:05 VERB PuppetManager resolveName(wechaty-puppet-oicq)
CustomError: Cannot find module '/home/anelderly/wechaty-getting-started/node_modules/wechaty-puppet-oicq/dist/esm/src/mod.js' imported from /home/anelderly/wechaty-getting-started/node_modules/wechaty/dist/esm/src/puppet-manager.js
    at finalizeResolution (/home/anelderly/wechaty-getting-started/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:383:11)
    at moduleResolve (/home/anelderly/wechaty-getting-started/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:818:10)
    at Object.defaultResolve (/home/anelderly/wechaty-getting-started/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:929:11)
    at /home/anelderly/wechaty-getting-started/node_modules/ts-node/src/esm.ts:68:38
    at Generator.next (<anonymous>)
    at /home/anelderly/wechaty-getting-started/node_modules/ts-node/dist/esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/anelderly/wechaty-getting-started/node_modules/ts-node/dist/esm.js:4:12)
    at resolve (/home/anelderly/wechaty-getting-started/node_modules/ts-node/dist/esm.js:32:16)
    at Loader.resolve (internal/modules/esm/loader.js:86:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:230:28)
    at Loader.import (internal/modules/esm/loader.js:165:28)
    at importModuleDynamically (internal/modules/esm/translators.js:114:35)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at Function.resolveName (file:///home/anelderly/wechaty-getting-started/node_modules/wechaty/src/puppet-manager.ts:118:26)
    at Function.resolve (file:///home/anelderly/wechaty-getting-started/node_modules/wechaty/src/puppet-manager.ts:72:33)
    at Wechaty.initPuppet (file:///home/anelderly/wechaty-getting-started/node_modules/wechaty/src/wechaty.ts:394:48)
    at Wechaty.start (file:///home/anelderly/wechaty-getting-started/node_modules/wechaty/src/wechaty.ts:722:18)
17:30:05 ERR Wechaty start() exception: Cannot find module '/home/anelderly/wechaty-getting-started/node_modules/wechaty-puppet-oicq/dist/esm/src/mod.js' imported from /home/anelderly/wechaty-getting-started/node_modules/wechaty/dist/esm/src/puppet-manager.js
17:30:05 ERR StarterBot Error: Cannot find module '/home/anelderly/wechaty-getting-started/node_modules/wechaty-puppet-oicq/dist/esm/src/mod.js' imported from /home/anelderly/wechaty-getting-started/node_modules/wechaty/dist/esm/src/puppet-manager.js
```

Error  still  thrown after install wechaty-puppet-oicq@0.1.5 (esm version)

```
[anelderly@pubgyes wechaty-getting-started]$ npm ls wechaty-puppet-oicq
wechaty-getting-started@0.13.13 /home/anelderly/wechaty-getting-started
└── wechaty-puppet-oicq@0.1.5
```

**Comment by huan** [comment]
I saw you have just merged the ESM PR, which I believe what you are testing now is not the latest code.

I have bumped the version to v0.1.6 , please wait the GitHub Action publish the latest version version, and try again.

**Comment by anaivebird** [comment]
0.1.5 is published after I checkout esm branch, so I believe it is lastest.

Also, 0.1.6's publish action is failed in github

**Comment by huan** [comment]
> Also, 0.1.6's publish action is failed in github

You need to set the secret for this repository in settings, using the environment variable name `NPM_TOKEN`

Please send another push to the repo after you have set it, and then to see if the CI can work as expected 

Also, this means that we have never published the ESM version before: the DevOps pipeline is not working yet.

https://github.com/wechaty/wechaty-puppet-oicq/blob/17ae76b4a295215d3163aebb745d01f4eb5ea1a0/.github/workflows/npm.yml#L101

**Comment by anaivebird** [comment]
I have set NPM_TOKEN in secrets, and rerun git action of 0.1.6, but it still not work.
![image](https://user-images.githubusercontent.com/29398611/134492713-7e711785-0a40-466e-aee2-4f9700cc72fc.png)

```
npm ERR! code ENEEDAUTH
npm ERR! need auth This command requires you to be logged in.
npm ERR! need auth You need to authorize this machine using `npm adduser`

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-09-23T10_30_49_114Z-debug.log
Error: Process completed with exit code 1.

```

**Comment by huan** [comment]
Instead of setting it in "Environment secrets", you should set it in "Repository secrets"

Please try again and I believe it will work.

**Comment by anaivebird** [comment]
It works, 0.1.6 has been published by github action. But why latest version is still 0.0.1, while next version is 0.1.6
![image](https://user-images.githubusercontent.com/29398611/134518274-08990ec9-4ba9-47ce-b1e8-3402246bbeb1.png)

**Comment by huan** [comment]
The `@latest` version is the stable version, which will only be updated when the minor version number is even.

For example, if you want to publish a `@latest` version, you need to bump the version from v0.1 to v0.2 , please feel free to try it.

If the minor version is odd, then it will only update the `@next` version, which means it's the alpha stage.

**Comment by huan** [comment]
Congratulations!

Please keep improving it, for example, wrapper all the log messages into our `log.verbose()` so that it will not output too many debug messages.

I hope the ding/dong bot can be ready to use soon! (and it would be great if it can also reply a image)
