### ISSUE TITLE
OnMessage binding using puppet works, but binding with bot in wechaty-getting-started broken

### ISSUE THREAD

**Issue by anaivebird** [wechaty/wechaty-puppet-oicq#6]
ding-dong not work if using wechaty-getting-started project with following command:
```
export WECHATY_PUPPET=wechaty-puppet-oicq
export WECHATY_LOG=verbose
npm start
```

The log inside OnMessage is never called, which means `bot.on('message', onMessage)` failed.
```
async function onMessage (msg: Message) {
  log.info('StarterBot', msg.toString())

  if (msg.text() === 'ding') {
    await msg.say('dong')
  }
}
```

But when directly using `npm run start` on wechaty-puppet-oicq project, the onMessage event is called successfully which means `puppet.on('message', onMessage)` works. 
```
async function onMessage (payload: EventMessagePayload) {
  const msgPayload = await puppet.messagePayload(payload.messageId)
  if (msgPayload.text === 'ding') {
    await puppet.messageSendText(msgPayload.fromId!, 'dong')
  }
}
```
Any suggestion on debugging this problem?

@huan

**Comment by huan** [comment]
Please paste the verbose output message for those two cases.

You can enable the verbose output log message by:

```
export WECHATY_LOG=verbose
```

**Comment by anaivebird** [comment]
for the wechaty-getting-started part:
```
[anelderly@pubgyes wechaty-getting-started]$ export WECHATY_PUPPET_OICQ_QQ=1962099319
[anelderly@pubgyes wechaty-getting-started]$ export WECHATY_PUPPET=wechaty-puppet-oicq
[anelderly@pubgyes wechaty-getting-started]$ export WECHATY_LOG=verbose
[anelderly@pubgyes wechaty-getting-started]$ npm start

> wechaty-getting-started@0.13.13 start /home/anelderly/wechaty-getting-started
> cross-env NODE_OPTIONS='--no-warnings --loader=ts-node/esm' node examples/ding-dong-bot.ts

12:33:24 INFO Config registering process.on("unhandledRejection") for development/debug
12:33:24 VERB Config constructor()
12:33:24 VERB wechaty-puppet-service monkeyPatchMetadataFromHttp2Headers()
12:33:24 VERB ResolverWechaty setup()
12:33:24 VERB Wechaty constructor()
12:33:24 VERB StateSwitch constructor(Wechaty, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
12:33:24 VERB StateSwitch constructor(WechatyReady, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
12:33:24 VERB Wechaty on(scan, listener) registering... listenerCount: 0
12:33:24 VERB Wechaty on(login, listener) registering... listenerCount: 0
12:33:24 VERB Wechaty on(logout, listener) registering... listenerCount: 0
12:33:24 VERB Wechaty on(message, listener) registering... listenerCount: 0
12:33:24 VERB Wechaty <wechaty-puppet-oicq>(ding-dong-bot) start() v0.69.58 is starting...
12:33:24 VERB Wechaty id: cku7vfgeo0000eymiffg735d9
12:33:24 VERB StateSwitch <WechatyReady> off(true) <- (true)
12:33:24 VERB StateSwitch <Wechaty> on(pending) <- (false)
12:33:24 VERB MemoryCard constructor("ding-dong-bot")
12:33:24 VERB MemoryCard getStorage() for storage type: N/A
12:33:24 VERB getStorage name: ding-dong-bot, options: {"type":"file"}
12:33:24 VERB StorageFile constructor(ding-dong-bot, ...)
12:33:24 VERB StorageBackend constructor(ding-dong-bot, { type: file })
12:33:24 VERB MemoryCard load() from storage: StorageFile</home/anelderly/wechaty-getting-started/ding-dong-bot.memory-card.json>
12:33:24 VERB StorageFile load() from /home/anelderly/wechaty-getting-started/ding-dong-bot.memory-card.json
12:33:24 VERB Wechaty init() getRavenDsn() return undefined, skipped.
12:33:24 VERB Wechaty initPuppet() 
12:33:24 VERB MemoryCard multiplex(puppet)
12:33:24 VERB MemoryCard static multiplex(MemoryCard<ding-dong-bot>, puppet)
12:33:24 VERB MemoryCard constructor({"name":"ding-dong-bot","multiplex":{"name":"puppet","parent":{"options":{"name":"ding-dong-bot"},"name":"ding-dong-bot","payload":{"\rpuppet\nPUPPET_WECHAT":[{"name":"MM_WX_SOUND_STATE","value":"1","domain":"wx.qq.com","path":"/","expires":-1,"size":18,"httpOnly":false,"secure":false,"session":true,"sameParty":false,"sourceScheme":"Secure","sourcePort":443},{"name":"MM_WX_NOTIFY_STATE","value":"1","domain":"wx.qq.com","path":"/","expires":-1,"size":19,"httpOnly":false,"secure":false,"session":true,"sameParty":false,"sourceScheme":"Secure","sourcePort":443},{"name":"mm_lang","value":"en","domain":".wx.qq.com","path":"/","expires":1632424665,"size":9,"httpOnly":false,"secure":true,"session":false,"sameParty":false,"sourceScheme":"Secure","sourcePort":443}]},"multiplexNameList":[],"storage":{"name":"ding-dong-bot","options":{"type":"file"},"absFileName":"/home/anelderly/wechaty-getting-started/ding-dong-bot.memory-card.json"}}}})
12:33:24 VERB PuppetManager resolve({puppet: wechaty-puppet-oicq, puppetOptions: undefined})
12:33:24 VERB PuppetManager resolveName(wechaty-puppet-oicq)
12:33:24 VERB Puppet constructor({}) #0
12:33:24 VERB StateSwitch constructor(PuppetOICQ, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
12:33:24 VERB MemoryCard constructor(undefined)
12:33:24 VERB MemoryCard getStorage() for storage type: N/A
12:33:24 VERB MemoryCard load() from storage: N/A
12:33:24 VERB MemoryCard load() no storage
12:33:24 VERB Puppet constructor() watchdog timeout set to 60 seconds
12:33:24 VERB PuppetOICQ constructor("{}")
12:33:24 VERB Puppet setMemory()
12:33:24 VERB Wechaty initPuppetEventBridge(Puppet#0<PuppetOICQ>(ding-dong-bot))
12:33:24 VERB Wechaty initPuppetEventBridge() puppet.on(friendship) (listenerCount:0) registering...
12:33:24 VERB Wechaty initPuppetEventBridge() puppet.on(login) (listenerCount:0) registering...
12:33:24 VERB Wechaty initPuppetEventBridge() puppet.on(logout) (listenerCount:0) registering...
12:33:24 VERB Wechaty initPuppetEventBridge() puppet.on(message) (listenerCount:0) registering...
12:33:24 VERB Wechaty initPuppetEventBridge() puppet.on(room-invite) (listenerCount:0) registering...
12:33:24 VERB Wechaty initPuppetEventBridge() puppet.on(room-join) (listenerCount:0) registering...
12:33:24 VERB Wechaty initPuppetEventBridge() puppet.on(room-leave) (listenerCount:0) registering...
12:33:24 VERB Wechaty initPuppetEventBridge() puppet.on(room-topic) (listenerCount:0) registering...
12:33:24 VERB Wechaty initPuppetEventBridge() puppet.on(scan) (listenerCount:0) registering...
12:33:24 VERB Wechaty initPuppetEventBridge() puppet.on(dirty) (listenerCount:0) registering...
12:33:24 VERB Wechaty initPuppetEventBridge() puppet.on(dong) (listenerCount:0) registering...
12:33:24 VERB Wechaty initPuppetEventBridge() puppet.on(error) (listenerCount:0) registering...
12:33:24 VERB Wechaty initPuppetEventBridge() puppet.on(heartbeat) (listenerCount:0) registering...
12:33:24 VERB Wechaty initPuppetEventBridge() puppet.on(ready) (listenerCount:0) registering...
12:33:24 VERB Wechaty initPuppetEventBridge() puppet.on(reset) (listenerCount:0) registering...
12:33:24 VERB Wechaty wechatifyUserModules(Puppet#0<PuppetOICQ>(ding-dong-bot))
12:33:24 VERB PuppetOICQ start()
12:33:24 VERB StateSwitch <PuppetOICQ> on(pending) <- (false)
[2021-10-01T12:33:24.590] [MARK] [Android:1962099319] - ----------
[2021-10-01T12:33:24.591] [MARK] [Android:1962099319] - Package Version: oicq@1.20.2 (Released on 2021/9/12)
[2021-10-01T12:33:24.591] [MARK] [Android:1962099319] - View Changelogs：https://github.com/takayama-lily/oicq/releases
[2021-10-01T12:33:24.591] [MARK] [Android:1962099319] - ----------
[2021-10-01T12:33:24.594] [MARK] [Android:1962099319] - 正在探索可用服务器...
12:33:24 VERB StateSwitch <PuppetOICQ> on(true) <- (pending)
12:33:24 VERB Wechaty on(heartbeat, listener) registering... listenerCount: 0
12:33:24 VERB StateSwitch <Wechaty> on(true) <- (pending)
12:33:24 INFO StarterBot Starter Bot Started.
[2021-10-01T12:33:24.787] [MARK] [Android:1962099319] - connecting to 129.226.103.59:443
[2021-10-01T12:33:24.800] [MARK] [Android:1962099319] - 129.226.103.59:443 connected
[2021-10-01T12:33:25.029] [MARK] [Android:1962099319] - Welcome, 划水狗 ! 初始化资源...
[2021-10-01T12:33:25.132] [MARK] [Android:1962099319] - 加载了9个好友，3个群。
[2021-10-01T12:33:25.132] [MARK] [Android:1962099319] - 初始化完毕，开始处理消息。
[2021-10-01T12:33:46.413] [INFO] [Android:1962099319] - recv from: [Private: 847817381(friend)] ding
MoiqpQAAJ3z6EncBYVaPqQA=
12:33:46 VERB Message static load(MoiqpQAAJ3z6EncBYVaPqQA=)
12:33:46 VERB Message constructor(MoiqpQAAJ3z6EncBYVaPqQA=) for class WechatifiedMessage
12:33:46 VERB Message ready()
12:33:46 VERB Puppet messagePayload(MoiqpQAAJ3z6EncBYVaPqQA=)
12:33:46 VERB Contact load(847817381) init pool
12:33:46 VERB Contact ready() this.wechaty.puppet.contactPayload(847817381) exception: Method not implemented.
12:33:46 ERR Config ###########################
12:33:46 ERR Config unhandledRejection: Error: Method not implemented.
    at PuppetOICQ.contactRawPayload (file:///home/anelderly/wechaty-getting-started/node_modules/wechaty-puppet-oicq/src/puppet-oicq.ts:265:11)
    at PuppetOICQ.contactPayload (file:///home/anelderly/wechaty-getting-started/node_modules/wechaty-puppet/src/puppet.ts:730:35)
    at WechatifiedContact.ready (file:///home/anelderly/wechaty-getting-started/node_modules/wechaty/src/user/contact.ts:833:48)
    at WechatifiedMessage.ready (file:///home/anelderly/wechaty-getting-started/node_modules/wechaty/src/user/message.ts:867:47)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async PuppetOICQ.<anonymous> (file:///home/anelderly/wechaty-getting-started/node_modules/wechaty/src/wechaty.ts:492:15) [object Promise]
12:33:46 ERR Config ###########################
12:33:46 ERR Config process.on(unhandledRejection) promise.catch(Method not implemented.)
Config Error: Method not implemented.
    at PuppetOICQ.contactRawPayload (file:///home/anelderly/wechaty-getting-started/node_modules/wechaty-puppet-oicq/src/puppet-oicq.ts:265:11)
    at PuppetOICQ.contactPayload (file:///home/anelderly/wechaty-getting-started/node_modules/wechaty-puppet/src/puppet.ts:730:35)
    at WechatifiedContact.ready (file:///home/anelderly/wechaty-getting-started/node_modules/wechaty/src/user/contact.ts:833:48)
    at WechatifiedMessage.ready (file:///home/anelderly/wechaty-getting-started/node_modules/wechaty/src/user/message.ts:867:47)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async PuppetOICQ.<anonymous> (file:///home/anelderly/wechaty-getting-started/node_modules/wechaty/src/wechaty.ts:492:15)
```

**Comment by anaivebird** [comment]
for the wechaty-puppet-oicq part:
```
[anelderly@pubgyes wechaty-puppet-oicq]$ npm run start

> wechaty-puppet-oicq@0.1.6 start /home/anelderly/wechaty-puppet-oicq
> cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node examples/ding-dong-bot.ts

12:35:38 VERB Puppet constructor({}) #0
12:35:38 VERB StateSwitch constructor(PuppetOICQ, "{"log":{"enableTimestamp":true,"logLevel":4,"prefixFilter":{}}}")
12:35:38 VERB MemoryCard constructor(undefined)
12:35:38 VERB MemoryCard getStorage() for storage type: N/A
12:35:38 VERB MemoryCard load() from storage: N/A
12:35:38 VERB MemoryCard load() no storage
12:35:38 VERB Puppet constructor() watchdog timeout set to 60 seconds
12:35:38 VERB HotImport callerResolve(., /home/anelderly/wechaty-puppet-oicq/node_modules/wechaty-puppet/dist/src/puppet.js)
12:35:38 VERB Puppet constructor() childClassPath=/home/anelderly/wechaty-puppet-oicq/file:/home/anelderly/wechaty-puppet-oicq/src
12:35:38 VERB PuppetOICQ constructor("{}")
12:35:38 VERB PuppetOICQ start()
12:35:38 VERB StateSwitch <PuppetOICQ> on(pending) <- (false)
[2021-10-01T12:35:38.446] [MARK] [Android:1962099319] - ----------
[2021-10-01T12:35:38.447] [MARK] [Android:1962099319] - Package Version: oicq@1.20.2 (Released on 2021/9/12)
[2021-10-01T12:35:38.447] [MARK] [Android:1962099319] - View Changelogs：https://github.com/takayama-lily/oicq/releases
[2021-10-01T12:35:38.447] [MARK] [Android:1962099319] - ----------
[2021-10-01T12:35:38.449] [MARK] [Android:1962099319] - 正在探索可用服务器...
12:35:38 VERB StateSwitch <PuppetOICQ> on(true) <- (pending)

Puppet Version: 0.1.6

Please wait... I'm trying to login in...


[2021-10-01T12:35:38.545] [MARK] [Android:1962099319] - connecting to 129.226.103.59:443
[2021-10-01T12:35:38.553] [MARK] [Android:1962099319] - 129.226.103.59:443 connected
[2021-10-01T12:35:38.736] [MARK] [Android:1962099319] - Welcome, 划水狗 ! 初始化资源...
[2021-10-01T12:35:38.845] [MARK] [Android:1962099319] - 加载了9个好友，3个群。
[2021-10-01T12:35:38.845] [MARK] [Android:1962099319] - 初始化完毕，开始处理消息。
[2021-10-01T12:35:41.925] [INFO] [Android:1962099319] - recv from: [Private: 847817381(friend)] ding
MoiqpQAAJ30h9qJ2YVaQHQA=
12:35:41 VERB Puppet messagePayload(MoiqpQAAJ30h9qJ2YVaQHQA=)
{"fromId":847817381,"id":"MoiqpQAAJ30h9qJ2YVaQHQA=","text":"ding","timestamp":1633062941926,"toId":847817381,"type":7}
[2021-10-01T12:35:42.073] [INFO] [Android:1962099319] - send to: [Private: 847817381 / message_id: MoiqpQAAAA7SH0PuYVaQHgE=]

```

**Comment by huan** [comment]
According to the log message:

> 12:33:46 VERB Contact ready() this.wechaty.puppet.contactPayload(847817381) exception: Method not implemented.

It's clearly telling you that the `contactPayload` method needs to be implemented before it can be fully workable.

When a message has been received, the Wechaty needs to load all the payload from the talker, listener by their id, which means that the `contactPayload()` needs to be implemented.

**Comment by anaivebird** [comment]
Thanks for detailed information. Any way to debug wechaty-getting-started with puppet without publish npm package(install the package locally)? Otherwise, any changes on code for debugging require a new version published on npm.

**Comment by huan** [comment]
You are welcome.

For easy debugging your npm module locally, you can use `npm link` , see https://docs.npmjs.com/cli/v7/commands/npm-link

**Comment by anaivebird** [comment]
Is `contactPayload` method a must for wechaty-getting-started to work with the puppet?
It seems that wechaty-puppet-lark didn't implement it on [puppet-lark.ts](https://github.com/wechaty/wechaty-puppet-lark/blob/df78984f3b0078bd51a6066339232b2fdc88cfc3/src/puppet-lark.ts#L288).
Also it needs to get all people in the contact list to implement `contactPayload`, which couldn't be found on [oicq's document](https://github.com/takayama-lily/oicq/wiki/91.API%E6%96%87%E6%A1%A3#%E8%8E%B7%E5%8F%96%E7%BE%A4%E7%BE%A4%E5%91%98%E5%88%97%E8%A1%A8%E5%92%8C%E8%B5%84%E6%96%99)

**Comment by huan** [comment]
A full implemented puppet should implement all abstract methods correctly.

However, you can cherry pick and just make the wechaty-getting-started repo works as expected, and feel free to finish your work by studying other puppets.

Looking forward to seeing the oicq puppet works for our dong/dong not soon!

**Comment by anaivebird** [comment]
Thanks for suggestion, I will try to work around it.

Also, something broken after using `npm link`
https://github.com/wechaty/wechaty-puppet-oicq/issues/11#issue-1014268590

**Comment by anaivebird** [comment]
Fixed.

Totally fixed after calling `this.login()` correctly with `this.login(this.qq.toString())`

Thanks a lot for spending your time tracking my debugging process.
![image](https://user-images.githubusercontent.com/29398611/135799810-79ba402a-af38-43e5-bba9-e588d879ddc2.png)

_Originally posted by @anaivebird in https://github.com/wechaty/wechaty-puppet-oicq/issues/11#issuecomment-933160337_
